# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [2]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [3]:
a = np.random.random(10)
b = np.random.random(10)
print((a+b)*(-1*a/2))

[-0.08637901 -0.11265763 -0.64061408 -0.27544361 -0.00089153 -0.01839919
 -0.52544362 -0.71426631 -0.0889687  -0.03940071]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [6]:
z = np.random.uniform(0,10,10)

print (z - z%1)
print (np.floor(z))
print (np.ceil(z)-1)
print (z.astype(int))
print (np.trunc(z))

[3. 7. 6. 7. 9. 0. 9. 8. 4. 0.]
[3. 7. 6. 7. 9. 0. 9. 8. 4. 0.]
[3. 7. 6. 7. 9. 0. 9. 8. 4. 0.]
[3 7 6 7 9 0 9 8 4 0]
[3. 7. 6. 7. 9. 0. 9. 8. 4. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [7]:
z = np.zeros((5,5))+np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [8]:
def generator():
    for x in range(10):
        yield x

z = np.fromiter(generator(),dtype=int)
print(z)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [9]:
np.linspace(0,1,12, endpoint=True)[1:11]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [10]:
#print(np.sort(np.random.random(10)))도 가능
z=np.random.random(10)
z.sort()
print(z)

[0.11861647 0.194991   0.51978251 0.5208799  0.56813674 0.72740695
 0.73680043 0.77416778 0.87395429 0.97989907]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [11]:
z = np.arange(5)
np.add.reduce(z)

10

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [12]:
a = np.random.randint(0,5,5)
b = np.random.randint(0,5,5)

# np.array_equal(): 두 배열의 모양과 요소가 동일
equal = np.array_equal(a,b)
print(equal)

# np.allclose(): 각 요소가 동일 (오차 허용)
equal = np.allclose(a,b)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [14]:
#immutable: 변경할 수 없는
z = np.random.randint(0,10,5)
z.flags.writeable = False
print(z)
z[0]=9

[4 3 3 0 8]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

참고:
def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(rho, phi)

def pol2cart(rho, phi):
    x = rho * np.cos(phi)
    y = rho * np.sin(phi)
    return(x, y)

In [15]:
z = np.random.random((10,2))
x,y = z[:,0], z[:,1]
rho = np.sqrt(x**2+y**2)
phi = np.arctan2(y,x)
print(rho,phi)

[1.29682262 0.34675073 1.17509458 1.06770494 0.50762337 0.29182207
 0.22181271 0.42284732 1.1189667  0.9507169 ] [0.77297839 1.43148054 0.98964876 0.37796285 1.55387135 1.45792702
 0.01933663 0.55585369 0.7646883  0.53101787]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [16]:
z = np.random.random(10)
print(z)
z[np.argmax(z)]=0
print(z)

[0.76702591 0.58020453 0.95893172 0.68721162 0.66876901 0.92115552
 0.62621511 0.78851987 0.9957932  0.30603221]
[0.76702591 0.58020453 0.95893172 0.68721162 0.66876901 0.92115552
 0.62621511 0.78851987 0.         0.30603221]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [17]:
z = np.zeros((5,5), [('x',float),('y',float)])
print(z)

z['x'], z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))

print(z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [20]:
x = np.arange(8)
y = x + 0.5
#np.func.outer() 찾아보기
c = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(c))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [21]:
#질문
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [22]:
#np.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None, *, legacy=None)
z = np.arange(100)
print(z)
np.set_printoptions(threshold=np.inf)
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [23]:
z = np.arange(100)
v = np.random.uniform(0,100)

index = (np.abs(z-v)).argmin()
print(z[index])

5


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [53]:
z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\MINJIP~1\AppData\Local\Temp/ipykernel_28752/2569712299.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [32]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0],Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)


[[0.         0.63404194 0.59019997 0.43839642 0.71706426 0.89534547
  0.64187646 0.9769032  0.33990131 0.6690573 ]
 [0.63404194 0.         0.76952159 0.25686548 0.73125548 0.38014875
  0.28005821 0.34618546 0.56499776 0.29549615]
 [0.59019997 0.76952159 0.         0.77089605 0.19100972 0.75463305
  0.54641297 0.99543936 0.27689741 0.99237162]
 [0.43839642 0.25686548 0.77089605 0.         0.79604031 0.6214238
  0.44277601 0.5919523  0.50982334 0.24234469]
 [0.71706426 0.73125548 0.19100972 0.79604031 0.         0.62723709
  0.46844826 0.89698168 0.37782302 0.99118148]
 [0.89534547 0.38014875 0.75463305 0.6214238  0.62723709 0.
  0.25958225 0.29802845 0.67915268 0.65916558]
 [0.64187646 0.28005821 0.54641297 0.44277601 0.46844826 0.25958225
  0.         0.44994829 0.42453836 0.56886184]
 [0.9769032  0.34618546 0.99543936 0.5919523  0.89698168 0.29802845
  0.44994829 0.         0.85383628 0.5142588 ]
 [0.33990131 0.56499776 0.27689741 0.50982334 0.37782302 0.67915268
  0.42453836 0.853836

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [33]:
z = np.arange(10, dtype=np.float32)
z.astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [34]:
from io import StringIO

# Fake file
f = StringIO("""1, 2, 3, 4, 5\n
6, , , 7, 8\n
, , 9,10,11\n""")

z = np.genfromtxt(f, delimiter=",", dtype=np.int32)
print(z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [35]:
#enumerate: 반복문 사용 시 몇 번째 반복문인지 확인 가능; 인덱스 번호+컬렉션 원소 
#np.ndenumerate()
z = np.arange(8).reshape(2,4)

for index, value in np.ndenumerate(z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [36]:
#2D Gaussian distribution: similar to a normal function but in place of x, use square-roots of squares of 1D variables
x, y= np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-((d-mu)**2 / (2.0 * sigma ** 2)))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [37]:
n = 10
p = 3
z = np.ones((n,n))
np.put(z, np.random.choice(range(n*n), p, replace=False),0)
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [38]:
x = np.random.rand(2,4)
y = x - x.mean(axis=1, keepdims=True)
print(y)

[[-0.50708619 -0.03841886  0.1723516   0.37315345]
 [-0.1828589   0.25673738 -0.35833232  0.28445384]]


#### 59. How to sort an array by the nth column? (★★☆)

In [39]:
z = np.random.randint(0,9,(2,4))

print(z)
print(z[z[:,1].argsort()])
print(z[z[:,2].argsort()])

n=3
print(z[z[:,n].argsort()])

[[0 2 3 0]
 [1 1 3 5]]
[[1 1 3 5]
 [0 2 3 0]]
[[0 2 3 0]
 [1 1 3 5]]
[[0 2 3 0]
 [1 1 3 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [40]:
z = np.random.randint(0,7,(2,4))
print(z)
print((~z.any(axis=0)).any())
#np.any(조건) :배열의 데이터 중 조건과 맞는 데이터가 하나라도 있으면 True, 전혀 없으면 False
#np.all(조건) - 배열의 모든 데이터가 조건과 맞으면 True, 하나라도 다르면 False

[[4 4 2 2]
 [1 6 6 3]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [41]:
#[0,1) 균등분포에서 10개 랜덤 추출
z = np.random.uniform(0,1,10)
mean = 0.5 #균등분포 평균
#np.ndarray.flat[]: 배열의 사본을 1차원으로 반환 후 순서대로 index 부여
#평균으로부터 가장 가까운 값; 오차가 가장 적은 배열 값
near = z.flat[np.abs(z - mean).argmin()]
print(near)

0.5132507473753726


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [42]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)

#iterator: 반복자
#np.nditer: 반복 횟수의 최대 확인하기
it = np.nditer([a,b,None])

for x,y,z in it: 
    z[...] = x + y

print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [43]:
class TempObjectForReadValues:
    def __init__(self):
        self.read_elements = [None] * 10

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [44]:
z = np.ones(10)
a = np.random.randint(0,len(z),20)
np.add.at(z,a,1)
print(a)

print(z)

[1 4 2 7 8 0 8 6 1 0 0 8 6 7 9 2 4 2 8 5]
[4. 3. 4. 1. 3. 2. 3. 3. 5. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [51]:
X = [1,2,3,4,5,6]
I = [3,2,8,5,6,1]
#np.bincount(): ndarray에서 non negative integer 각각의 빈도수를 카운트, 0부터 가장 큰 값까지 각각의 발생 빈도수를 체크
F = np.bincount(I,X)
print(F)

[0. 6. 2. 1. 0. 4. 5. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [52]:
img = np.random.randint(0,2,(16,16,3)).astype(np.ubyte)
F = img[...,0]*(256*256) + img[...,1]*256 + img[...,2]
print(len(np.unique(F)))

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)